export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_PROF = 'UPDATE_PROFILE_PROF';
export const DELETE_PROFILE = 'DELETE_PROFILE';

export const UPDATE_MSM = 'UPDATE_MSM';
export const UPDATE_MOJ = 'UPDATE_MOJ';
export const UPDATE_MCN = 'UPDATE_MCN';
export const UPDATE_DN = 'UPDATE_DN';

export const UPDATE_MHP = 'UPDATE_MHP';
export const UPDATE_SV = 'UPDATE_SV';

export const SET_PROFESSIONAL_INFO = 'SET_PROFESSIONAL_INFO';
export const PROF_SIGN_OUT = 'PROF_SIGN_OUT';
export const NEW_NOTIFICATION_COUNT = 'NEW_NOTIFICATION_COUNT';
export const NEW_NOTIFICATION_COUNT_MINUS = 'NEW_NOTIFICATION_COUNT_MINUS';

export const RESET_NOTIFICATION_COUNT = 'RESET_NOTIFICATION_COUNT';

export const PROF_REQUEST_ADD = 'PROF_REQUEST_ADD';
export const PROF_REQUEST_SEEN = 'PROF_REQUEST_SEEN';
export const PROF_REQUEST_REMOVE = 'PROF_REQUEST_REMOVE';
export const DELETE_ALL_PROF_REQUEST = 'DELETE_ALL_PROF_REQUEST';

export const SET_UNREAD_NOTIFICATION_COUNT = 'SET_UNREAD_NOTIFICATION_COUNT';
