module.exports.constants = {
  APPOINTMENT_REQUESTED: 'APPOINTMENT_REQUESTED',
  REQUESTED: 'REQUESTED',
  APPOINTMENT_ACCEPTED: 'APPOINTMENT_ACCEPTED',
  SUGGEST_A_SCALE: 'SUGGEST_A_SCALE',
  SCALE_FILLUP_BY_USER: 'SCALE_FILLUP_BY_USER',
  ROLES: {
    USER: 'user',
    PROFESSIONAL: 'professional',
  },
  FORGET_PASSWORD: 'forget-password',
  VERIFY_EMAIL: 'email-verification',
};
