export default {
  WELCOME: 'Welcome',
  USER_REGISTER_CONSENT: 'UserRegisterConsent',
  REGISTER_WITH_EXTRA_INFORMATION: 'AdditionalInformation',
  ONBOARDING_GUIDELINE: 'StartingGuideline',
  TEST_PAGE: 'CircularQuiz',
  LOGIN: 'Login',
  REGISTER: 'Register',
  HOMEPAGE: 'Homepage',
  VIDEO_SCREEN: 'VideoScreen',
  PROFILE: 'Profile',
  QUALITY_LIFE: 'Quality Life',
  VIDEO_EXERCISE_LIST: 'VideoExerciseList',
  VIDEO_EXERCISE: 'VideoExercise',
  THREE_SCALES: 'ThreeScales',
  UPDATE_USER_PROFILE: 'UpdateProfile',
  PROFESSIONALS_LIST: 'AllProfessionals',
  PROFESSIONAL_DETAILS: 'professionalDetails',
  PROF_LOGIN: 'PROF_LOGIN',
  PROF_REGISTRATION_CONSENT: 'RegisterConsentPro',
  WAIT_FOR_VERIFICATION: 'AccountConfirmation',
  PROF_REGISTER_STEP_1: 'RegisterPro',
  PROF_REGISTER_STEP_2: 'RegisterProStep2',
  PROF_REGISTER_STEP_3: 'RegisterProStep3',
  PROF_REGISTER_STEP_4: 'RegisterProStep4',
  PROF_HOMEPAGE: 'ProHomepage',
  PROF_LOGIN: 'LoginPro',
  PROF_PROFILE: 'ProfileProf',
  PROF_UPDATE_PROFILE: 'UpdateProfilePorf',
  PROF_ASSESSMENT_TOOLS: 'ProAssessments',
  PROF_ASSESSMENT_TOOL_DETAILS: 'ProAssessmentDetails',
  PROF_CLIENT_REQUEST: 'ClientRequestPro',
  PROF_RESPONSE_CLIENT_REQUEST: 'ResponseClientRequest',

  USER_APPOINTMENT_TAKEN: 'AppointmentSuccess',

  USER_TYPE: 'USER',
  PROF_TYPE: 'PROF',

  SPECIAL_LOGOUT_ACTION: ':: logout ::',

  APPOINTMENT_REQUESTED: 'APPOINTMENT_REQUESTED',
  REQUESTED: 'REQUESTED',
  APPOINTMENT_ACCEPTED: 'APPOINTMENT_ACCEPTED',
  APPOINTMENT_STATUS: 'AppointmentStatus',
  PROFESSIONALS_CLIENT: 'ProMyClients',
  CLIENT_PROFILE: 'ClientProfile',
  ASK_FOR_TEST: 'AskForTest',
  TEST: 'Test',
  HELP_CENTER: 'HelpCenter',
  SETTINGS: 'Setting',
  ABOUT_US: 'AboutUs',
  PRIVACY_POLICY: 'PrivacyPolicy',
  QUIZ_RESULT_OUT_OF_100: 'QuizResultOutOf100',
};
